# Generated by Django 5.1.1 on 2024-11-19 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('nim', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('gender', models.CharField(choices=[('male', 'Laki-Laki'), ('female', 'Perempuan')], max_length=20)),
                ('major', models.CharField(blank=True, max_length=100)),
                ('classroom', models.CharField(blank=True, max_length=100)),
                ('generation', models.PositiveIntegerField(blank=True, null=True)),
                ('personal_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('file_sptjm', models.FileField(blank=True, upload_to='app_coop/static/document/sptjm/')),
                ('file_proof_consultation', models.FileField(blank=True, upload_to='app_coop/static/document/proof_consultation/')),
                ('profile_image', models.FileField(blank=True, upload_to='app_coop/static/image/profile_image/')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('mahasiswa', 'Mahasiswa')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConfirmationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=50)),
                ('file_report', models.FileField(upload_to='app_coop/static/document/confirmation_reports/')),
                ('intern_type', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=20)),
                ('mentor_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=255)),
                ('pic_name', models.CharField(max_length=100)),
                ('pic_position', models.CharField(max_length=100)),
                ('company_address', models.TextField()),
                ('file_proof_confirm', models.FileField(upload_to='app_coop/static/document/proof_confirmations/')),
                ('nim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accept', 'Diterima'), ('rejected', 'Tidak Diterima'), ('review', 'Sedang Ditinjau')], max_length=20)),
                ('nim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id_intv', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('file_cv', models.FileField(upload_to='app_coop/static/document/cv_files/')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews_by_email', to=settings.AUTH_USER_MODEL)),
                ('nim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews_by_nim', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id_notification', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_related', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkList',
            fields=[
                ('id_list', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('nim', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
