# Generated by Django 5.1.1 on 2024-11-19 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='confirmationstatus',
            old_name='nim',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='name',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='worklist',
            old_name='name',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='confirmationfile',
            name='nim',
        ),
        migrations.AddField(
            model_name='confirmationfile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentees', to='app_coop.mentor'),
        ),
    ]
