# Generated by Django 5.1.1 on 2024-11-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coop', '0005_alter_confirmationfile_file_proof_confirm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationfile',
            name='file_proof_confirm',
            field=models.FileField(upload_to='document/proof_confirmations/'),
        ),
        migrations.AlterField(
            model_name='confirmationfile',
            name='file_report',
            field=models.FileField(upload_to='document/confirmation_reports/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='file_proof_consultation',
            field=models.FileField(blank=True, upload_to='document/proof_consultation/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='file_sptjm',
            field=models.FileField(blank=True, upload_to='document/sptjm/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.FileField(blank=True, upload_to='image/profile_image/'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='file_cv',
            field=models.FileField(upload_to='document/cv_files/'),
        ),
    ]
